creativecommons/chooser

- src/index.html
- src/index.js
- src/scripts/choose-a-license.js
- src/scripts/page-controls.js
- src/scripts/scripts.js
- src/styles/styles.css
Adds the license chooser functionality to page.
**Checklist:**
index.md`).
Version 1.1
Suite D4700
of my …
> [WIP] Add chooser functionality

- build/vue-loader.conf.js
- package-lock.json
- package.json
- src/App.vue
- src/i18n.js
- src/locales/App.json
- src/main.js
Fixes #27
The integration of CC Chooser with Vocabulary was only partially complete in that two dependencies namely `vue-i18n` and `@kazupon/vue-i18n-loader` had not been installed. This PR installs these dependencies, sets up i18n with an example and thus resolves the issue of `$t` not being found.
**Checklist:**
index.md`).
Version 1.1
Suite D4700
By making a contribution to this project, I …
> Complete the incomplete integration of Vocabulary with Chooser

- test/unit/specs/components/IconSelector.spec.js
add unit test for IconSelector.vue component
IconSelector.vue component is responsible for rendering the license, it accept:
- props: `{ id: String, icon: String , value: boolean }`
- click event which triggers input event with true or false.
**_example:_**
- props: `{ id: 'sa', icon: 'sa', value: 'true' }`
- click event.
**_result:_**
- triggers input event with false, which means unselect the SA license.
**_Note_**:
**default props:**
- SA's value could be true or false, which means it could be auto selected or no.
- NC and ND's value must be true when mounting the component.
**Checklist:**
index.md`).
Version 1.1
Copyright (C) 2004, 2006 …
> add unit test for IconSelector.vue component

- src/App.vue
Fixes #31 
Fixed footer credits style
**Checklist:**
index.md`).
Version 1.1
Suite D4700
of my knowledge, …
> Vocabulary styles being overriden by custom styling 

- package-lock.json
- package.json
- src/App.vue
- src/components/HelpSection.vue
- src/components/SelectedLicenseCode.vue
- src/components/SelectedLicenseDropdown.vue
- src/components/Stepper.vue
- src/main.js
Fixes #62 and #64 
Set up Google analytics for chooser. The following events are tracked:
- **User opening the page**
- **User clicking on any of the 'Help' button** 
_Information sent:_ `HelpSection.clicked.<button-title>`
- **User opening Attribution Details step**, when we can assume that the user has selected a license : 
_Information sent:_ `Stepper.licenseSelected.<short name of selected license>`
- **User selecting a license from the dropdown**
_Information sent:_ `LicenseDropdown.licenseSelected.<short name of selected license>`
- **User copying attribution details**
_Information sent:_ 
`Attribution.copied.<Stringified JSON: license: short name of selected license, codeType: one of html/rich-text, fieldsFilled: <fieldName: true/false>>`
**Checklist:**
index.md`). …
> [WIP] Set up Google analytics

- src/components/HelpSection.vue
- src/locales/en.json
Signed-off-by: Olga Bulat <obulat@gmail.com>
Fixes #100
Changed the full license name to 'Attribution-NonCommercial International 4.0'
**Other information**
License [Legal Code page](https://creativecommons.org/licenses/by-nc/4.0/legalcode) states the name of the license as 'Creative Commons Attribution-NonCommercial 4.0 International Public License', but the[ license information pages](https://creativecommons.org/licenses/by-nc/4.0/), that actually communicate to the public human-readable description of the license, only state 'Attribution-NonCommercial'. 
**Checklist:**
index.md`).
Version 1.1
Copyright (C) 2004, 2006 The Linux Foundation …
> Edit full license name in 'How Licenses are Communicated' modal to match the icons

- .eslintrc.js
- src/App.vue
- src/components/AttributionDetailsStep.vue
- src/components/CopyrightWaiverStep.vue
- src/components/DropdownStep.vue
- src/components/Feedback.vue
- src/components/FirstStep.vue
- src/components/Footer.vue
- src/components/Header.vue
- src/components/HelpSection.vue
- src/components/LicenseCode.vue
- src/components/LicenseDetailsCard.vue
- src/components/LicenseDropdown.vue
- src/components/LicenseIcons.vue
- src/components/LicenseUseCard.vue
- src/components/LocaleChooser.vue
- src/components/PrintMediaLicenseCode.vue
- src/components/Step.vue
- src/components/Stepper.vue
- src/components/WebLicenseCode.vue
Signed-off-by: Olga Bulat <obulat@gmail.com>
Prepare for fixing  #98 
This PR introduces recommended settings for vue, including removing unnecessary 'this' in templates, and indent consistency in both templates and javascript. Eslint settings are also changed from essential to recommended.
**Other information**
**Checklist:**
index.md`).
Version 1.1
Suite D4700
By making a …
> Lint with eslint vue/recommended settings

- src/utils/license-utilities.js
- tests/unit/specs/utils/license-uilities.test.js
Fixes #125 
I have added various tests, I think 126 in total.
I have also updated license-utilities for an edge case:`attrToFull({BY: undefined})` acts similar to `attrToShort({BY: undefined})`
index.md`).
```
Version 1.1
Suite D4700
have the right to submit it under the …
```
> Add license-utilities tests + update attrToFull to act like attrToShort

- tests/unit/FirstStep.spec.js
Fixes #115 
Added unit test cases for the component FirstStep.js using Jest
index.md`).
```
Version 1.1
Suite D4700
of my knowledge, is covered under an appropriate open source
license and I have the right …
```
> Addition of unit tests for FirstStep.js

- src/components/LicenseCode.vue
Modified namespace prefix from "dc" to "dct" within the span element for the title, to match the xmlns:dct declaration for the Dublin Core Terms namespace.
Unless I'm misunderstanding the intent of the code, the span element for the title is trying to refer to the Dublin Core Terms "title" property, in which case I believe it should be referring to the "dct" namespace prefix declared within one of its ancestor elements.
index.md`).
```
Version 1.1
Suite D4700
license document, …
```
> Corrected Dublin Core Terms namespace

- src/components/LocaleChooser.vue
Fixes #140 by @achilep
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based upon previous work that, to the …
```
> [WIP]: Fix lang logo to not overlay popup

- src/components/HelpSection.vue
- tests/e2e/specs/LicenseCode.js
- tests/e2e/specs/LicenseDetailsCard.js
Fixes #153 by @obulat and removes to return the tracked object
The e2e tests of `LicenseCode.vue` and `LicenseDetailsCard.vue` started to break because of some click handler error this `PR` fixes them. Also since the $ga was removed from the tests of `Helpsection.vue` I removed the modifications that I did to the `clickHandler` function to return the object which I used to test it. At this point when I ran npm run test all the unit and e2e tests were passing
---
---
index.md`).
<details>
```
Version 1.1
Suite D4700
San …
```
> Fixed the tests of LicenseCode.vue and LicenseDetailsCard.vue

- tests/e2e/specs/CopyrightWaiverStep.js
- tests/unit/specs/components/CopyrightWaiverStep.spec.js
Related  #133 by @akmadian 
- Adds unit tests
- Adds e2e tests
- [x ] My pull request has a descriptive title (not a vague title like `Update
index.md`).
- [x ] My code follows the established code style of the repository.
- [x ] I added tests for the changes I made (if applicable).
<details>
```
Version 1.1
Suite D4700
By making a …
```
> Adds unit and e2e tests for CopyrightWaiverStep Component

- tests/e2e/specs/DropdownStep.js
- tests/unit/specs/components/DropdownStep.spec.js
Fixes #114 by @akmadian 
- Adds unit and e2e tests for the DropdownStep Component
- cd into git branch _ft-dropdown-unit_
- To run unit tests run the command ```npm run test: unit DropdownStep.spec.js``` on the terminal
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The …
```
> Adds unit and e2e tests for DropdownStep Component

- src/App.vue
- src/components/LocaleChooser.vue
Positioning of LocaleChooser is updated with css grid properties. This PR updates styling of the App and LocaleChooser components to be mobile-first.
Fixes #164 by @JackieBinya 
Update to the LocaleChooser and App styles: makes them mobile-first, and fixes the issue of not showing locale chooser on screens smaller than 1024px.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```
> Make LocaleChooser responsive

- package-lock.json
- package.json
- src/components/HelpSection.vue
Modal positioning is affected by its parent elements, so to make it render correctly, vue-simple-portal moves rendered modal html to the bottom of the page.
Fixes #165 by @obulat and #159 by @SaurabhAgarwala 
Currently, modals are rendered as child elements of help component, which makes them use styling of the parent elements. Because of this, various positioning and z-index problems arise, including the issues mentioned in #165:
- select ::after element is not clickable because it's underneath another element. So, we cannot select a language for the site.
- footer text is visible through the modal.
VueSimplePortal enables us to render the modal html to an element at the bottom of the page, outside other parent elements, and solves these issues.
index.md`). …
> Fix Modal positioning

- src/App.vue
- src/components/LicenseCopy.vue
- src/components/Stepper.vue
Fixes #162 by @annatuma 
- Changes sites' main content background color from white to #F5F5F5 as stipulated in the design mocks
*  After I changed the site's main content background color to #F5F5F5. I noticed several bugs in the site's appearance. Further details about bugs are described below:
1. `White gap between <main> and footer elements`: To resolve this issue I removed the `margin-top`  of `5rem` and gave the `<main>` a `padding-bottom` of `5rem` so as to preserve the original look of the site.
2. `Selected language no longer visible in the locale-chooser component`:  Resolved
index.md`).
<details>
```
Developer Certificate of …
```
> Changes site's main content background color from white to #F5F5F5

- tests/e2e/specs/LicenseCode.js
- tests/e2e/specs/LicenseDetailsCard.js
- tests/unit/specs/components/App.spec.js
- tests/unit/specs/components/__snapshots__/App.spec.js.snap
Fixes #124 by @akmadian 
This PR adds unit tests for the App component. I didn't include any e2e tests because there's really no interactivity with the App component itself.
I couldn't think of many test cases so what I've got now feels somewhat anemic. Please let me know if you can think of any other cases and I'll implement them!
Run `npm run test`
index.md`).
<details>
```
Version 1.1
Suite D4700
license document, but changing …
```
> Add unit tests for App component

- src/components/LicenseCode.vue
- src/utils/license-utilities.js
- tests/unit/specs/components/LicenseCode.spec.js
- tests/unit/specs/utils/license-uilities.test.js
Fixes #188 by @fkohrt
Replaces all occurrences of the `rel` attribute with `property` where appropriate; i.e. where the inner content of the element is targeted (and not the `href` or `src` as implied by `rel`).
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The contribution was …
```
> Use "property" instead of "rel" where appropriate; fixes #188

- src/components/AttributionDetailsStep.vue
- src/locales/en.json
- tests/unit/specs/components/__snapshots__/AttributionDetailsStep.spec.js.snap
- tests/unit/specs/components/__snapshots__/Stepper.spec.js.snap
Fixes #198 by @fkohrt 
Update the wording of the form input labels and placeholders and their order to make them more clear and consistent.
index.md`).
<details>
```
Version 1.1
Suite D4700
have the right to submit it …
```
> Update AttributionDetailsStep form for clarity

- tests/unit/specs/components/LicenseCode.spec.js
- tests/unit/specs/components/LicenseDropdown.spec.js
- tests/unit/specs/components/__snapshots__/LicenseDropdown.spec.js.snap
- tests/unit/specs/components/__snapshots__/Stepper.spec.js.snap
Signed-off-by: Hrishikesh Agarwal <hrishikeshagarwalv@gmail.com>
Fixes #120  by @akmadian 
Added unit test for component LicenseDropdown.vue
Added snapshot test for the component.
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole or in part by …
```
> added unit test for LicenseDropdown component

- src/components/LicenseCopy.vue
Fixes #206 by @panchovm
This fixes the copy button in the plain text tab under "Use your license" so it will actually copy the text.
The cause seemed to be the duplicate IDs between the two different tabs. This pull request creates separate IDs for the text elements. In addition, some other duplicate IDs were converted to classes.
This code seems like it could use an overhaul to make the tabs more flexible. The current code relies on a lot of assumptions (like there being only two tabs, Web and print, with the Web tab having two sub-tabs under it).
index.md`).
<details>
```
Version 1.1
Copyright (C) 2004, …
```
> Fix copy button in plain text tab under "Use your license"

- src/store/index.js
Fixes #208 by @panchovm
This PR fixes the error when if a user selects ND, SA was not removed. ShareAlike can only be selected when ND is not selected.
The change was introduced in Vuex mutation.
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole …
```
> Remove ShareAlike when a user selects ND

- package-lock.json
- package.json
- src/components/AttributionDetailsStep.vue
- src/components/LicenseCopy.vue
- src/components/LicenseDropdown.vue
- src/components/Stepper.vue
- src/main.js
- src/styles/vocab.scss
- tests/unit/specs/components/__snapshots__/AttributionDetailsStep.spec.js.snap
- tests/unit/specs/components/__snapshots__/FirstStep.spec.js.snap
- tests/unit/specs/components/__snapshots__/LicenseDropdown.spec.js.snap
Related to #229 by @obulat
This PR updates the Vocabulary version to the most recent one. It also imports it and registers the Vue Vocabulary components in `main.js` so that they can be used throughout the app without importing individual components. The import path is set to the file itself for now,  before the PR solving the path issue is merged into Vue Vocabulary.
Buefy version is also updated to fix an error caused by a breaking change.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```
> Update Vue Vocabulary to latest version

- src/components/Stepper.vue
- tests/unit/specs/components/Stepper.spec.js
- tests/unit/specs/components/__snapshots__/Stepper.spec.js.snap
Fixes #222 by @obulat
This PR replaces buefy button with a Vocabulary VButton in the Stepper "Previous" and "Next" buttons.
At the moment, the color of the button is overridden by Bulma or Buefy 'is-success' color. A PR submitted to Vocabulary repo will ensure that the color matches the Vocabulary designs.
index.md`).
<details>
```
Version 1.1
Suite D4700
Developer's Certificate …
```
> Use Vocabulary VButton in the Stepper

- src/locales/ru.json
- tests/e2e/specs/LicenseCode.js
- tests/unit/specs/components/LicenseCode.spec.js
Fixes #193 by @fkohrt alongside #200
Changes `www.author.com` to `https://janedoe.com`
I changed the implementation of a test at [`tests/unit/specs/components/LicenseCode.spec.js`](https://github.com/creativecommons/chooser/pull/245/commits/2a4e827962c5ba7a451a782320cc3582f33d27ae#diff-45017824acdbe5c2c634203f4bec474c9089e95e54f2ab86ccd0b3f3521ae0a2L88-R88) so this should be verified to be ok.
index.md`).
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute verbatim …
```
> Use domain names instead of URLs and harmonize example creator

- src/App.vue
- src/components/FooterSection.vue
- src/components/HelpSection.vue
- src/components/StepHeader.vue
- src/components/Stepper.vue
- tests/unit/specs/components/App.spec.js
Fixes #319  by @obulat
It sets the headings' visual styles in an accessible way and thus enhances accessibility.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```
> Accessibility: Setting headings' visual styles in an accessible way 

- src/utils/xmp.js
Fixes #333 by @fkohrt
Replaces `&#34;` by `&quot;`
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based upon …
```
> Use predefined XML entity in generated XMP

- src/components/CopyrightWaiverStep.vue
- src/components/Stepper.vue
- src/store/index.js
- tests/unit/specs/components/CopyrightWaiverStep.spec.js
Fixes #323 
This PR moves the state of the `CopyrightWaiverStep` checkboxes into Vuex, so they persist when returning to the step from the following steps. This also establishes a pattern for steps with multiple checkboxes that we can use in #315 
This PR also models best practices for unit testing in Vue.js, namely, that _simulated user input should be used to test Vue internals._ In this case we're asserting that simulated checking of checkboxes triggers a Vue custom 'change' event in our Step component.
index.md`).
<details>
```
Version 1.1
Copyright (C) 2004, 2006 The Linux Foundation and its …
```
> Fix persistence of `CopyrightWaiverStep` checkboxes

- package-lock.json
- package.json
Signed-off-by: Anik Das <anikdas0811@gmail.com>
Fixes #367 by @brylie 
- removed `node-sass`
- installed `sass`
- there were some warnings during build process which I'm trying to find out if I can fix
- ![image](https://user-images.githubusercontent.com/16396161/147278553-9d51cf89-9b14-47ce-b975-cbddd8aa036b.png)
- `npm run serve` and `npm run build` run without issues
- all tests pass
index.md`).
<details>
``` …
```
> fix: #367, replace node-sass with sass

- src/components/StepHeader.vue
Fixes #401  by @MuluhGodson 
This PR ensures that when chooser is launched, each step is marked as completed or in progress [with a green coloring] only when the user has gone through them or is on them.
index.md`).
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute verbatim …
```
> Fix step header colors.

- src/components/ChooserModal.vue
- src/components/HelpSection.vue
Fixes #464  by @soustab10 
Fixed the Improper padding by changing padding in media queries.
Problem:
Solution:
index.md`).
<details>
```
Version 1.1
Suite D4700
Developer's Certificate of …
```
> Fixes Improper padding in "Confused? Need Help?" modals #464

- src/components/LicenseUseCard.vue
Added `word-wrap and max-width` 
Fixed text overflow issue in the rich text box
Fixes #463 by @soustab10 
My changes breaks the long word in separate parts if the text gets too long and I have fixed a max-width for that component.
index.md`).
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy …
```
> Fixed overflow issue

- .gitignore
- Dockerfile
- README.md
- docker-compose.yml
improve behavior of docker containers and document local cypress testing
- Resolves issue where NGINX (`http://localhost:8888`) would result in 403 after build
- Document how to run Cypress tests locally
- Improve node caching behavior (store cache in repo so it isn't lost every time the container is stopped)
- Rendered readme:
- Old/current [`README.md`](https://github.com/creativecommons/chooser/blob/5dd9c45c7bec2145f7f9ede90423e03781ce7c84/README.md)
- New/PR [`README.md`](https://github.com/creativecommons/chooser/blob/c593fb59ca3f9de8fd256ee51cf04d9cafe0c4ad/README.md)
Now with documented local Cypress tests!
<details>
<summary>Cypress test results</summary>
```
====================================================================================================
(Run Starting) …
```
> improve behavior of docker containers and document local cypress testing

- src/components/StepHeader.vue
- Fixes #543 by @valentin-huebner
Changes `reversed` in `StepHeader.vue` to be a Boolean value instead of a function. In the below code it is expected to be Boolean but was always truthy, even though it should be false for `name == 'BY'`. This caused the completed step caption to be incorrectly reversed for BY.
index.md`).
<details>
```
Version 1.1
1 …
```
> Fix bug responsible for showing the wrong completed step caption for BY

- src/components/AppModal.vue
- src/components/ChooserModal.vue
- Fixes #546 by @akshathere
This PR fixes the issue with the cc logo icon appearing of the close icon on the modals. This is largely a temporary fix.
The issue was caused by how vocabulary handles the `.icon*` classes, which replaces icons that are not in vocabulary with the cc icon as a default.
From careful inspection of the code, the modal was handled by an `app-modal` component, which was imported from the `@creativecommons/vocabulary-components` npm package. 
Because this package is based on the vue implementation of the legacy vocabulary code, it meant that I couldn't access or edit the source component directly. Hence, I implemented a new modal component, `AppModal` which is the new wrapper for the `ChooserModal` component contents.  This new component now has a corrected …
> [Fix] icon overlay issue of the close button in modal

- src/index.html
- src/style.css
* defines a basic semantic markup "component" for `license recommendation`, and a general `license` sub-component within, with appropriate sub-elements. 
* creates a localized implementation of the cc license icons for use with the icon-attach helper class with the relevant cc-icons.svg sprite sheet.
* corrects the page title
* corrects the path for the page-level cc license icons (they now load instead of 404)
* zeros out the `<template>` for now to be used later with JS
Things remain messy and unfinished, but we now have a basic area within which to populate a relevant license recommendation when JS functionality is added later.
I tried to keep the semantics simple, but I think it might get improvements later. It made sense that the conditions definitions broken down within the various …
> correct `h1` to "Chooser", build out semantic html for "results" area

- src/scripts.js
- src/style.css
* sets baseline objects, arrays, etc.
*  confines various logic parts to functions
* defines possible state paths through the stepper (of which there are 14 valid path routes)
* tracks the parts of the path on change (updates `state.parts`)
* updates the full `state.current` on change
* compares the `state.current` to `state.possibilities` to determine license rec or error
* roughly renders out the recommended license within the "license recommendation" area
* includes working comments and some `console.log` statements for testing and debugging purposes
* ties stepper choice behavior to a dynamic state path that amends at each `fieldset` change
* when a fieldset is changed, the current state is amended to reflect the updated `state.parts`, and then combined into the full updated …
> setup baseline file for stepper logic, hide/show steps, adds minimal license rec capacity

- src/index.html
- src/scripts.js
- src/style.css
* adds a `<template>` for each `license`
* loads each `license` `<template>` based on `state.props.license` when known
* cycles through various rendering pathways for the UX steps (don't show SA if ND, etc).
* sets a `state.props.cursor` to track current step, and clear any selections left from a previous journey through the steps afterward.
* correctly selects, and renders the appropriate `license` based on valid pathways of selection through the stepper
* sets better defaults on various steps, so explicit decisions have to be made on steps > 0.
* adds additional functions to fully flesh out setting the remaining sub-items of `state`, tracking that and aligning both the `state` with the various UI elements found within the steppers, to keep them in sync along chosen pathways
* there's …
> add baseline `templates` for the various licenses, to load dynamically in "rec area" when a matching `license` is found from `state.current`

- src/index.html
- src/scripts.js
- src/style.css
* hides other formats for later work, focuses only on the "plain text" marking format
* adds appropriate modularized functions to render the "mark your work" section if a matching `license` if found
* adds a new watcher to track changes in "attribution details" and update in "plain text" "mark your work" format
*  adds new `state.props.licenseShort` and `state.props.licenseURL` to the state obj for use in formatting or other areas
* adds new `state.props.attribution` to store attribution details for onChange dynamic access
* sets up an empty mark `<template>` for use later with possible inclusion of WebComponent implementation for mark formats
* establishes baseline core structure functionality, so that it can be built out further modularly within this process, and allow enough …
> render "mark you work" section, add logic and `state` to support

- src/index.html
- src/scripts.js
- src/style.css
* fixes duplicate input name error
* strip html from inputs in Attribution Details area.
* adds rough read-only fields to the Attribution Details area (trying for now, may rework or change/remove later)
* wraps the Mark formats section in `<details>`, and moves towards a collapsible section, rather than tabs more better cross-viewport UX and to simplify the implementation more (tabs don't have a native element implementation and often assume a detachment of "title" and "body" that can lead to odd semantics)
* adds baseline responsiveness to build from
index.md`).
For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is …
> improve formats UX (markup and styling), add `details/summary` to mediums and formats

- src/index.html
- src/scripts.js
- src/style.css
* improves the overall UX and display of the chooser pathway fieldsets, as well as the Attribution Details area.
* adds toggle behavior to display long name of tool
* adds copy behavior to copy contents of mark format to clipboard
* various UX improvements to text, sizing, spacing, and placement
* initial flow of js now only fires once the body is fully loaded (to ensure elements are all present to query)
* baseline placeholder html mark format is set to be build out more specifically
This remains unfinished, but is approaching a final clean up PR soon.
index.md`).
For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is …
> improve ux, add copy behavior, add short/long name toggle behavior
