creativecommons/chooser

.gitignore
CODE_OF_CONDUCT.md

Added a gitignore, removed a changelog link from the code of conduct.
**Checklist:**
index.md`).
Version 1.1
Suite D4700
(b) The contribution is based upon previous work …

Add .gitignore, remove changelog link from code of conduct.

---

.gitignore
package.json

Add .gitignore and package.json. Pretty basic at this point, but more will be added once coding properly starts.
For Breno and Alden: Does this look good, should I add anything that I've missed?
**Checklist:**
index.md`).
Version 1.1
Suite D4700
have the …

Add .gitignore and package.json

---

CONTRIBUTING.md
package-lock.json
package.json
src/index.html
src/styles/bulma-mods.css
src/styles/sass/bulma-mods.scss

Add Bulma and node-sass (for Bulma customization). Update package.json with needed scripts.
**Checklist:**
index.md`).
Version 1.1
Suite D4700
(b) The contribution is based …

Add Bulma and node-sass

---

src/index.html
src/styles/sass/bulma-mods.scss
src/styles/styles.css

This is a pretty big change to the page's layout. The educational section's layout has been changed into a two row design, with icon related content on the bottom, and the question buttons on the top. Additionally, the entire educational section's position on the page has been swapped with the chooser section's. The chooser is now at the top of the page.
Here's a picture:
**Checklist:**
index.md`).
Version 1.1
Suite D4700
license document, but changing it is not …

Update Educational Section Layout, Update Page Layout

---

package-lock.json
package.json
src/index.html
src/scripts/page-controls.js
src/styles/sass/bulma-mods.scss
src/styles/styles.css

Still a ways to go, but looking good so far.
**Checklist:**
index.md`).
Version 1.1
Suite D4700
of my knowledge, is …

[WIP] Add Mobile CSS

---

src/index.html
src/styles/styles.css

This branch will add and refine mobile CSS for phone and tablet breakpoints
**Checklist:**
index.md`).
Version 1.1
Suite D4700
(b) The contribution is based upon previous …

Add/ Refine Mobile CSS

---

src/index.html
src/index.js
src/scripts/HTML-generator.js
src/scripts/choose-a-license.js
src/styles/styles.css

This adds all HTML generator functionality.
**Checklist:**
index.md`).
Version 1.1
Suite D4700
of my …

Add HTML Generator Functionality

---

test/svgTransform.js
test/unit/jest.conf.js

Jest doesn't know how to handle files with `.svg` extension. So we need a transformer, that basically returns the same value, to be able to work with icon files.
**Other information**
**Checklist:**
index.md`).
Version 1.1
Suite D4700
have the right to …

Add svg file handling for jest

---

src/components/Chooser.vue
test/unit/specs/components/Chooser.spec.js

Fixes #33 
I implemented unit tests for the component trying to follow your approach, based on other components' tests.
This should cover all the main aspects of the code, I'll try to further expand it if something comes to my mind. Of course, feel free to ask if you think it's not enough or something's wrong, I'd be glad to continue helping.
**Checklist:**
index.md`).
Version 1.1
Suite D4700
Developer's …

Add Chooser component unit tests

---

README.md

Very small PR, changes serve script name in README from `npm run dev` to `npm run serve`
**Other information**
**Checklist:**
index.md`).
Version 1.1
Suite D4700
(b) The …

Update serve script name in README

---

src/components/Footer.vue

Fixes #108
I have modified the CSS rules.  Previously, hovering the links in the footer changed the colour to make it illegible to read.  Now, it has been fixed.  A hovered link is now underlined.
index.md`).
```
Version 1.1
Suite D4700
have the right to submit it under …
```

Fixing link hover colour problem.

---

tests/unit/specs/components/Step.spec.js
tests/unit/specs/components/__snapshots__/Step.spec.js.snap

Fixes #123 by @akmadian 
This PR adds unit tests for the Step component.
- This PR does not test every possible permutation of props because simply testing the logic in this particular component should cover almost all cases assuming the locale file has the proper schema.
- This PR does not include e2e tests because just about all permutations of step functionality are covered in the Stepper component's e2e tests.
Run `npm run test`
index.md`).
<details>
```
Version 1.1
Suite D4700
Everyone is …
```

Add unit tests for the Step component

---

src/components/HelpSection.vue

Fixes #189 by @fkohrt (Short name misses version number)
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based …
```

Fixes #189

---

src/components/FooterSection.vue

Fixes #207 by @panchovm
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based upon previous work that, to the …
```

Correct the attribution information for the CC0 license #207

---

.cc-metadata.yml

Since this repo will be will be actively maintained and continue to accept PRs, it makes sense to feature this repo on the Project List page on the CC OS site in place of ones that will not.
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole or …
```

Make the repo featured as it will be actively maintained

---

src/App.vue

Fixes #214 by @panchovm
This PR adds the breadcrumb stub. It will be replaced by a Vocabulary Vue component when it is available. Also, when the structure of the site and parent pages is clear, we will need to update them, too.
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The …
```

Add breadcrumb stub

---

README.md

Fixes #[issue number] by @[issue author]
Simple PR to add a reference to GitHub Pages in the README.
index.md`).
<details>
```
Version 1.1
Suite D4700
indicated in …
```

Update README.md with GitHub pages information

---

src/components/HelpSection.vue

Fixes #256 by @panchovm
It updates the styles of default links on hover.
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The …
```

hover_styles_updated

---

src/components/LicenseUseCard.vue

Fixes #265  by @
index.md`).
vi
sible errors.
<details>
```
Version 1.1
Suite D4700
of …
```

closes #265 text style in line tab component

---

src/components/HelpSection.vue

Fixes #283  by @obulat 
Updated tomato color in HelpSection
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The contribution is …
```

Updated tomato color in HelpSection

---

src/components/LicenseText.vue

Fixes #296 by @obulat
It makes the URL absolute in the section of **Link to Work** in **Attribution Details**
While assigning href property, just check if the URL has HTTP as a part of the string or not. If not assign it manually
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The …
```

Making link to work always as an absolute URL

---

.github/workflows/pull_request.yml

Fixes #284 by @obulat 
- Removes unnecessary file copying code from the deployment workflow
- Switches attribution of deployment commits from @obulat to @cc-open-source-bot (a best-practice for any automated code in CC repos)
We'll want to follow the deployment procedure referenced **here**: https://github.com/creativecommons/chooser/issues/284#issuecomment-763937439
index.md`).
<details>
```
Version 1.1
Suite D4700
license …
```

Update deployment workflow

---

.eslintrc.js
jsconfig.json
package-lock.json
package.json
tests/cypress/integration/AttributionDetails._spec.js
tests/cypress/integration/Stepper._spec.js

Fixes #336 by @zackkrida 
Updates our cypress test suite to include the newly added step for determining the appropriateness of cc licenses, also improves cypress developer experience by adding config for type intellisense. 
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The …
```

Add additional cypress config; Add appropriateness step to e2e tests

---

src/App.vue

Fixes #387  by @brylie 
This PR removes the breadcrump, title and descriptive text from Embedded builds.
The screenshot below shows the output when this project is build in embedded mode. This is preferable for integration downstream such as `project_creativecommons.org`.
index.md`).
<details>
```
Version 1.1
Suite D4700
San …
```

[src/App.vue] Remove breadcrumbs, title and text from embedded build.

---

package.json

Preparing package metadata for 0.1.0 release.

0.1.0 release prep

---

package-lock.json
src/App.vue
src/components/CopyTools.vue
src/components/DropdownStep.vue
src/components/HelpSection.vue

Fixes #398  by @brylie 
Fixes #399 by @MuluhGodson 
This PR removes obsolete code pertaining to Google Analytics.
index.md`).
<details>
```
Version 1.1
Suite D4700
Developer's Certificate of …
```

Remove Obsolete code

---

README.md

Fixes #515
Links are now embedded within their descriptive texts.
index.md`).
<details>
```
Version 1.1
Suite D4700
By making a contribution to this …
```

[Fix] links in the README

---

src/components/LicenseText.vue

- Fixes #495 by @beckej13820 
Fixes icon list not being rendered bug
- [Spread syntax (...) - JavaScript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax)
index.md`).
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute verbatim …
```

bug: fix missing license icons

---

src/index.html
src/scripts.js
src/style.css

* uses [Legal Tools namespaces](https://github.com/creativecommons/cc-legal-tools-data?tab=readme-ov-file#legal-tools-namespace) where appropriate for better naming across JS, CSS, and HTML
* changes the use of `license` to `tool` in most non-user facing situations. If naming is tied to copy, then it has remained the same (for example the question "Do you know which license you need?" is tied to the semantics of the state path and the HTML (which influences the naming conventions in the HTML, CSS, and JS). Until copy changes occur these naming use-cases must remain.
* moves markup templating for the plaint text into HTML as much as possible (later on I may find I have to reverse this if the other formats don't play well with `<template>` fragments and token replacement
Wherever reasonable …

alter namespaces, restructure code, amend plaint text markup to pull from `<template>` instead of raw JS

---

README.md
src/index.html
src/scripts.js
src/style.css

* Fixes incorrect label of `Creator Profile URL`
* adds and formats the `Help` section back, as `details`
* cleans up files (comments, logs, etc.)
* adds an `empty` element to prompt form completion
* resets `README.md` to baseline
* adds final HTML mark format
* adjusts UX, styles, spacing, and placement of items overall
* adds better placeholders for form stepper
* correctly displays copyright only if not `CC0`
* fix name of ShareAlike radios to correct behavior in stepper
index.md`).
<details> …

cleanup UX and files, enable `help` section, reset `README.md`, fix error with copyright display

---

README.md
src/style.css

* narrows the specificity scoping of styles to only the `chooser-page` context, so there is no unexpected style spill-over in other contexts.
* This is an upstream correction already addressed within `vocabulary-theme`:
- https://github.com/creativecommons/vocabulary-theme/pull/112
* updates `README.md` with better initial documentation
Once this PR is merged, the `refactor` branch should be able to be merged within `main` via PR.
index.md`).
<details>
<summary>Developer Certificate of …

correct specificity of styles, narrow scope to only `chooser-page` context, update `README.md`

---

src/index.html

- Fixes #588
- instances of `creativecommons.org` within Attribution Details placeholder data have been updated to instead be `example.com`
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

change placeholder url in attribution details to `example.com`

---

README.md

- bump version in `README.md` to `v1.1`
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) …
```

bump `README.md` version to `v1.1`
